/**
 * Build-time image manifest loader.
 *
 * The manifest is generated by `scripts/optimize-images.mjs` and maps
 * original image paths to optimized WebP variants with blur placeholders.
 *
 * During development, or before the pipeline has run, the manifest is
 * an empty object — all lookups return `undefined` and the
 * OptimizedImage component falls back to the original source path.
 */

export interface ImageManifestEntry {
  thumb: string;
  medium: string;
  large: string;
  width: number;
  height: number;
  blurDataURL: string;
}

export type ImageManifest = Record<string, ImageManifestEntry>;

let manifest: ImageManifest = {};

try {
  // The generated manifest is created by the prebuild step.
  // Using require() with try/catch so webpack marks it as optional;
  // if the file doesn't exist the catch block keeps manifest empty.
  manifest = require("../generated/image-manifest.json");
} catch {
  // Manifest not generated yet — all images fall back to originals
}

/** Get the full manifest (empty object if not yet generated). */
export function getImageManifest(): ImageManifest {
  return manifest;
}

/** Look up a single image entry by its source path. */
export function getManifestEntry(
  src: string
): ImageManifestEntry | undefined {
  return manifest[src];
}
