"""Scene manifest management for standard benchmark scenes.

Manages discovery, download status, path resolution, and format compatibility
for the bundled benchmark scenes (Cornell Box, Sponza, Stanford Bunny, etc.).

The manifest is a JSON file shipped with the package at
``data/scenes/manifest.json``.  It is **generated** from the repository's scene
catalog (``data/scenes/*.json``) by ``scripts/generate_scene_manifest.py`` so the
CLI and the website cannot describe a scene differently; edit the catalog, not
the manifest.

Actual scene files are large binary assets stored in ``~/.renderscope/scenes/``
and downloaded on demand via the ``renderscope download-scenes`` CLI command.

**On-disk layout.**  Each format has its own source and its own directory::

    <scenes_dir>/<scene_id>/<format>/<source.path>
    <scenes_dir>/<scene_id>/<format>/.renderscope-complete
    <scenes_dir>/<scene_id>/reference.exr

A scene is rarely published as one archive containing every format — the Cornell
Box's OBJ, PBRT and Mitsuba descriptions come from three unrelated hosts.  Giving
each format its own directory lets them be fetched, verified, replaced and
reasoned about independently, and means declaring a format implies a source that
can actually deliver it.
"""

from __future__ import annotations

import importlib.resources
import json
import logging
from pathlib import Path
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

logger = logging.getLogger(__name__)

# Default directory where scenes are stored on disk.
_DEFAULT_SCENES_DIR = Path.home() / ".renderscope" / "scenes"

# Marker file written into a format's directory after it installs successfully.
_COMPLETE_MARKER = ".renderscope-complete"


# ---------------------------------------------------------------------------
# Custom exceptions
# ---------------------------------------------------------------------------


class SceneNotFoundError(Exception):
    """Raised when a scene ID doesn't exist in the manifest."""

    def __init__(self, scene_id: str, available: list[str] | None = None) -> None:
        self.scene_id = scene_id
        msg = f"Scene '{scene_id}' not found in the manifest."
        if available:
            msg += f"\nAvailable scenes: {', '.join(available)}"
        super().__init__(msg)


class SceneNotDownloadedError(Exception):
    """Raised when trying to access a scene that hasn't been downloaded."""

    def __init__(self, scene_id: str) -> None:
        self.scene_id = scene_id
        super().__init__(
            f"Scene '{scene_id}' has not been downloaded.\n"
            f"Run 'renderscope download-scenes --scene {scene_id}' to download it."
        )


class FormatNotAvailableError(Exception):
    """Raised when a scene doesn't have the requested format."""

    def __init__(self, scene_id: str, fmt: str, available: list[str]) -> None:
        self.scene_id = scene_id
        self.format = fmt
        self.available_formats = available
        fmt_list = ", ".join(available) if available else "(none)"
        super().__init__(
            f"Scene '{scene_id}' is not available in '{fmt}' format.\nAvailable formats: {fmt_list}"
        )


class FormatNotDownloadedError(Exception):
    """Raised when a declared format has not been installed locally.

    Distinct from :class:`FormatNotAvailableError`: the scene does offer this
    format, it simply has not been fetched yet.  Formats download independently,
    so having the Cornell Box's OBJ says nothing about having its PBRT.
    """

    def __init__(self, scene_id: str, fmt: str) -> None:
        self.scene_id = scene_id
        self.format = fmt
        super().__init__(
            f"Scene '{scene_id}' has not been downloaded in '{fmt}' format.\n"
            f"Run 'renderscope download-scenes --scene {scene_id} --format {fmt}' to get it."
        )


# ---------------------------------------------------------------------------
# Pydantic models
# ---------------------------------------------------------------------------


class CameraInfo(BaseModel):
    """Camera configuration for a benchmark scene."""

    model_config = ConfigDict(extra="ignore")

    position: list[float]
    target: list[float]
    up: list[float]
    fov: float


class SceneReference(BaseModel):
    """Reference render metadata for quality comparison.

    ``renderer`` and ``samples`` nominate the ground truth for this scene:
    ``renderscope reference`` defaults to them so independently generated
    references stay comparable with one another.
    """

    model_config = ConfigDict(extra="ignore")

    renderer: str
    samples: int
    image: str  # Relative path to reference image within the scene directory.

    # --- Distribution (optional) ---
    # A reference render is generated by RenderScope rather than published
    # upstream, so unlike scene geometry there is no third party to fetch it
    # from. Once references are hosted somewhere, setting these lets a
    # contributor download one instead of spending hours regenerating it.
    url: str | None = None
    sha256: str | None = None


class SceneFormat(BaseModel):
    """Where one format of a scene comes from, and where it lands.

    Formats are acquired independently: the Cornell Box's OBJ, PBRT and Mitsuba
    descriptions are published by three unrelated hosts, so a single per-scene
    archive could never deliver all three.  Each format therefore carries its
    own source, its own checksum, and its own directory.
    """

    model_config = ConfigDict(extra="ignore")

    # Path to the scene's entry file relative to this format's directory,
    # exactly as the source archive lays it out.
    path: str

    # --- Source (optional: a format may be declared with no automated source) ---
    # Fully-qualified URL of the archive or loose file.  Supports ``http(s)://``
    # and ``file://`` schemes.
    url: str | None = None
    # Archive filename relative to a configured mirror (see ``SceneDownloader``
    # / ``RENDERSCOPE_SCENE_BASE_URL``).  Defaults to ``<scene_id>-<format>.tar.gz``.
    archive: str | None = None
    # Expected SHA-256 (hex) of the downloaded bytes.  When present, the
    # downloader verifies integrity and refuses to install a mismatched file.
    sha256: str | None = None
    # Download size in megabytes, measured from the source.
    size_mb: float = 0.0
    # Name to save the download under when the source is a single loose file
    # rather than an archive.  The Stanford Bunny is published as a bare
    # ``bunny.obj``; this records that it belongs at ``stanford-bunny.obj``.
    filename: str | None = None
    # Anything a user needs to know about this source.
    note: str | None = None


class SceneInfo(BaseModel):
    """Metadata for a standard benchmark scene."""

    model_config = ConfigDict(extra="ignore")

    id: str
    name: str
    description: str
    source: str
    source_url: str
    polygon_count: int
    tests: list[str]
    # "trivial", "low", "medium", "high", "extreme" — the catalog's vocabulary,
    # shared with the website so a scene is not rated twice.
    complexity: str
    formats: dict[str, SceneFormat]  # format_id -> source
    reference: SceneReference | None = None
    camera: CameraInfo
    download_size_mb: float

    # --- Dynamic state, populated by SceneManager ---
    is_downloaded: bool = False
    installed_formats: list[str] = Field(default_factory=list)


class SceneManifest(BaseModel):
    """Root model for the scene manifest JSON file."""

    model_config = ConfigDict(extra="ignore")

    version: str
    description: str = ""
    scenes: list[SceneInfo] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# SceneManager
# ---------------------------------------------------------------------------


class SceneManager:
    """Manages standard benchmark scenes — discovery, download status, and resolution.

    Loads the bundled manifest on initialization and provides methods to
    query scene metadata, check download status, and resolve file paths.
    """

    def __init__(self, scenes_dir: Path | None = None) -> None:
        self._scenes_dir = scenes_dir or _DEFAULT_SCENES_DIR
        self._manifest = self._load_manifest()

    @property
    def scenes_dir(self) -> Path:
        """Root directory where scene files are stored."""
        return self._scenes_dir

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def list_scenes(self) -> list[SceneInfo]:
        """Return all scenes from the manifest with download status populated."""
        return [self._with_state(scene) for scene in self._manifest.scenes]

    def get_scene(self, scene_id: str) -> SceneInfo:
        """Look up a single scene by ID.

        Raises:
            SceneNotFoundError: If the scene ID doesn't exist in the manifest.
        """
        for scene in self._manifest.scenes:
            if scene.id == scene_id:
                return self._with_state(scene)
        available = [s.id for s in self._manifest.scenes]
        raise SceneNotFoundError(scene_id, available=available)

    def _with_state(self, scene: SceneInfo) -> SceneInfo:
        """Return a copy of ``scene`` carrying its current on-disk state."""
        installed = [
            fmt for fmt in sorted(scene.formats) if self.is_format_downloaded(scene.id, fmt)
        ]
        return scene.model_copy(
            update={"is_downloaded": bool(installed), "installed_formats": installed}
        )

    def _has_marker(self, scene_id: str, fmt: str) -> bool:
        """Whether a format's completion marker is present."""
        return (self._scenes_dir / scene_id / fmt / _COMPLETE_MARKER).is_file()

    def format_dir(self, scene_id: str, fmt: str) -> Path:
        """Directory a format is installed into, whether or not it exists yet."""
        return self._scenes_dir / scene_id / fmt

    def scene_dir(self, scene_id: str) -> Path:
        """Directory holding every format of a scene, plus its reference render."""
        return self._scenes_dir / scene_id

    def is_format_downloaded(self, scene_id: str, fmt: str) -> bool:
        """Check whether one format of a scene is installed locally.

        A format counts as installed only when its directory holds the
        ``.renderscope-complete`` marker *and* the file the manifest promises,
        so a partial or superseded install is reported as missing rather than
        failing later inside a renderer.
        """
        try:
            scene = self._scene_or_raise(scene_id)
        except SceneNotFoundError:
            return False
        source = scene.formats.get(fmt)
        if source is None or not self._has_marker(scene_id, fmt):
            return False
        return (self.format_dir(scene_id, fmt) / source.path).is_file()

    def is_downloaded(self, scene_id: str) -> bool:
        """Check whether any format of a scene is installed locally.

        Formats are fetched independently, so a scene becomes usable as soon as
        one of them lands.  Callers that need a specific format should ask
        :meth:`is_format_downloaded`.
        """
        try:
            scene = self._scene_or_raise(scene_id)
        except SceneNotFoundError:
            return False
        return any(self.is_format_downloaded(scene_id, fmt) for fmt in scene.formats)

    def installed_formats(self, scene_id: str) -> list[str]:
        """Formats of a scene that are present and complete on disk, sorted."""
        try:
            scene = self._scene_or_raise(scene_id)
        except SceneNotFoundError:
            return []
        return [fmt for fmt in sorted(scene.formats) if self.is_format_downloaded(scene_id, fmt)]

    def describe_formats(self, scene_id: str) -> str:
        """A human-readable answer to "what can this scene actually be read as?".

        Reports what is on disk once a scene has been downloaded and what is
        merely declared before that, because an error message naming formats the
        caller does not have is worse than no message at all.
        """
        installed = self.installed_formats(scene_id)
        if installed:
            return ", ".join(installed)
        try:
            declared = sorted(self._scene_or_raise(scene_id).formats)
        except SceneNotFoundError:
            return "(none)"
        if not declared:
            return "(none)"
        return f"none downloaded (declared: {', '.join(declared)})"

    def get_scene_path(self, scene_id: str, fmt: str) -> Path:
        """Resolve the local file path for a scene in a specific format.

        Args:
            scene_id: Scene identifier (e.g., ``"cornell-box"``).
            fmt: Format identifier (e.g., ``"pbrt"``, ``"obj"``).

        Returns:
            Absolute path to the scene file on disk.

        Raises:
            SceneNotFoundError: If the scene doesn't exist in the manifest.
            FormatNotAvailableError: If the scene doesn't offer that format.
            SceneNotDownloadedError: If nothing has been downloaded for the scene.
            FormatNotDownloadedError: If this particular format is missing.
        """
        scene = self._scene_or_raise(scene_id)

        if fmt not in scene.formats:
            raise FormatNotAvailableError(scene_id, fmt, sorted(scene.formats))

        if not self.is_downloaded(scene_id):
            raise SceneNotDownloadedError(scene_id)

        if not self.is_format_downloaded(scene_id, fmt):
            raise FormatNotDownloadedError(scene_id, fmt)

        return self.format_dir(scene_id, fmt) / scene.formats[fmt].path

    def _scene_or_raise(self, scene_id: str) -> SceneInfo:
        """Return the raw manifest entry for ``scene_id`` without on-disk state.

        :meth:`get_scene` populates install state, which is computed from the
        very predicates that call this — going through it would recurse.
        """
        for scene in self._manifest.scenes:
            if scene.id == scene_id:
                return scene
        raise SceneNotFoundError(scene_id, available=[s.id for s in self._manifest.scenes])

    def get_reference_path(self, scene_id: str) -> Path | None:
        """Resolve the local path to a scene's reference image.

        Returns:
            The absolute path if available and downloaded, ``None`` otherwise.
        """
        scene = self.get_scene(scene_id)
        if scene.reference is None:
            return None
        if not self.is_downloaded(scene_id):
            return None

        ref_path = self._scenes_dir / scene.reference.image
        if ref_path.is_file():
            return ref_path
        return None

    def reference_target_path(self, scene_id: str) -> Path | None:
        """Where a scene's reference render *belongs*, whether or not it exists.

        :meth:`get_reference_path` answers "is there a reference to compare
        against" and returns ``None`` when the file is missing, which is the
        right answer for a reader but useless to a writer. Reference generation
        needs the destination, so producing a reference and consuming one agree
        on a single location instead of drifting apart.

        Returns ``None`` only when the manifest declares no reference for this
        scene, i.e. there is no canonical location to write to.
        """
        scene = self.get_scene(scene_id)
        if scene.reference is None:
            return None
        return self._scenes_dir / scene.reference.image

    def get_compatible_format(
        self,
        scene_id: str,
        supported_formats: list[str],
    ) -> str | None:
        """Find the best compatible format between a scene and a renderer.

        Given a scene and a list of formats a renderer supports, return
        the best matching format.  Native scene formats (pbrt, mitsuba_xml)
        are preferred over generic interchange formats (obj, gltf, ply).

        Args:
            scene_id: Scene identifier.
            supported_formats: Format IDs the renderer accepts.

        Returns:
            The best matching format ID, or ``None`` if no compatible format exists.
        """
        scene = self._scene_or_raise(scene_id)
        scene_formats = set(scene.formats)
        renderer_formats = set(supported_formats)

        # Find the intersection of available and supported formats.
        compatible = scene_formats & renderer_formats
        if not compatible:
            return None

        # A manifest entry promises a path, not a file, and formats download
        # independently — having the Cornell Box's OBJ says nothing about having
        # its PBRT. Once anything has been downloaded, what is on disk is the
        # truth: report a renderer as incompatible rather than letting it fail
        # later inside the renderer. Before any download there is nothing to
        # inspect, so the declared set stands — `benchmark --dry-run` still
        # needs to reason about the full run matrix.
        if self.is_downloaded(scene_id):
            compatible = {fmt for fmt in compatible if self.is_format_downloaded(scene_id, fmt)}
            if not compatible:
                return None

        # Prefer native scene formats over generic ones.
        native_priority = ["pbrt", "mitsuba_xml", "xml", "blend"]
        for native in native_priority:
            if native in compatible:
                return native

        # Fall back to any compatible format.
        return next(iter(sorted(compatible)))

    def get_scene_ids(self) -> list[str]:
        """Return a sorted list of all scene IDs in the manifest."""
        return sorted(s.id for s in self._manifest.scenes)

    def get_downloaded_scene_ids(self) -> list[str]:
        """Return IDs of scenes that have been downloaded locally."""
        return [s.id for s in self._manifest.scenes if self.is_downloaded(s.id)]

    def get_total_download_size(self) -> float:
        """Return the total download size (in MB) of all scenes."""
        return sum(s.download_size_mb for s in self._manifest.scenes)

    # ------------------------------------------------------------------
    # Download support
    # ------------------------------------------------------------------

    def prepare_scene_dir(self, scene_id: str) -> Path:
        """Create the local directory for a scene and return its path."""
        scene_dir = self._scenes_dir / self._scene_or_raise(scene_id).id
        scene_dir.mkdir(parents=True, exist_ok=True)
        return scene_dir

    def mark_format_downloaded(self, scene_id: str, fmt: str) -> None:
        """Write the completion marker for one installed format."""
        format_dir = self.format_dir(scene_id, fmt)
        format_dir.mkdir(parents=True, exist_ok=True)
        (format_dir / _COMPLETE_MARKER).write_text(
            f"Downloaded by RenderScope\nScene: {scene_id}\nFormat: {fmt}\n",
            encoding="utf-8",
        )

    def remove_format(self, scene_id: str, fmt: str) -> None:
        """Delete one format's local directory, if present.

        Used for a clean re-download: removing the directory (rather than just
        the marker) guarantees stale files from a previous archive don't linger.
        """
        import shutil

        format_dir = self.format_dir(scene_id, fmt)
        if format_dir.exists():
            shutil.rmtree(format_dir)

    def remove_scene(self, scene_id: str) -> None:
        """Delete a scene's entire local directory, if present.

        This also discards the scene's reference render, which lives beside the
        format directories and can cost hours to regenerate.
        """
        import shutil

        scene_dir = self._scenes_dir / scene_id
        if scene_dir.exists():
            shutil.rmtree(scene_dir)

    # ------------------------------------------------------------------
    # Manifest loading
    # ------------------------------------------------------------------

    @staticmethod
    def _load_manifest() -> SceneManifest:
        """Load the bundled scene manifest JSON.

        Resolution order:
        1. Monorepo layout: ``<project_root>/python/src/renderscope/data/scenes/manifest.json``
        2. Installed package data via ``importlib.resources``.
        """
        # Try monorepo layout first.
        mono_path = Path(__file__).resolve().parent.parent / "data" / "scenes" / "manifest.json"
        if mono_path.is_file():
            logger.debug("Loading scene manifest from monorepo: %s", mono_path)
            return SceneManager._parse_manifest(mono_path.read_text(encoding="utf-8"))

        # Fall back to installed package data.
        try:
            files = importlib.resources.files("renderscope.data.scenes")
            manifest_resource = files.joinpath("manifest.json")
            data = str(manifest_resource.read_text(encoding="utf-8"))
            logger.debug("Loading scene manifest from installed package data.")
            return SceneManager._parse_manifest(data)
        except (ModuleNotFoundError, FileNotFoundError, TypeError) as exc:
            logger.warning("Could not load scene manifest: %s", exc)
            return SceneManifest(version="0.0.0", scenes=[])

    @staticmethod
    def _parse_manifest(raw_json: str) -> SceneManifest:
        """Parse a manifest JSON string into a validated model."""
        data: dict[str, Any] = json.loads(raw_json)
        return SceneManifest.model_validate(data)
