"""Scientific colormaps for false-color visualization.

Provides pre-computed 256-entry lookup tables for the perceptually uniform
colormaps *viridis*, *inferno*, and *magma*.  These avoid the perceptual
pitfalls of older colormaps like *jet* and are suitable for error-map and
heatmap rendering.

If ``matplotlib`` is installed, exact colormap data is loaded from it.
Otherwise, high-quality approximations are generated by interpolating
control points derived from the original colormap definitions.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np

if TYPE_CHECKING:
    from numpy.typing import NDArray


# ---------------------------------------------------------------------------
# Control points for fallback colormaps (17 evenly-spaced samples each).
# These are interpolated to 256 entries at module load time.
# Format: list of (R, G, B) tuples with values in [0, 1].
# ---------------------------------------------------------------------------

_VIRIDIS_CTRL: list[tuple[float, float, float]] = [
    (0.267, 0.004, 0.329),
    (0.283, 0.141, 0.458),
    (0.254, 0.265, 0.530),
    (0.207, 0.372, 0.553),
    (0.164, 0.471, 0.558),
    (0.128, 0.567, 0.551),
    (0.120, 0.625, 0.530),
    (0.134, 0.658, 0.517),
    (0.173, 0.705, 0.478),
    (0.245, 0.757, 0.432),
    (0.329, 0.799, 0.378),
    (0.431, 0.838, 0.317),
    (0.550, 0.870, 0.245),
    (0.673, 0.887, 0.170),
    (0.797, 0.889, 0.101),
    (0.912, 0.863, 0.131),
    (0.993, 0.906, 0.144),
]

_INFERNO_CTRL: list[tuple[float, float, float]] = [
    (0.002, 0.001, 0.014),
    (0.042, 0.024, 0.148),
    (0.137, 0.022, 0.329),
    (0.258, 0.038, 0.406),
    (0.396, 0.082, 0.434),
    (0.523, 0.128, 0.420),
    (0.636, 0.169, 0.368),
    (0.735, 0.216, 0.330),
    (0.826, 0.282, 0.258),
    (0.893, 0.361, 0.184),
    (0.937, 0.453, 0.110),
    (0.965, 0.558, 0.044),
    (0.973, 0.669, 0.040),
    (0.953, 0.778, 0.157),
    (0.923, 0.865, 0.316),
    (0.945, 0.935, 0.509),
    (0.988, 0.998, 0.645),
]

_MAGMA_CTRL: list[tuple[float, float, float]] = [
    (0.002, 0.001, 0.014),
    (0.037, 0.028, 0.140),
    (0.114, 0.042, 0.326),
    (0.226, 0.059, 0.437),
    (0.342, 0.063, 0.479),
    (0.466, 0.086, 0.504),
    (0.578, 0.148, 0.504),
    (0.694, 0.224, 0.483),
    (0.798, 0.298, 0.468),
    (0.868, 0.378, 0.482),
    (0.920, 0.466, 0.510),
    (0.953, 0.561, 0.548),
    (0.974, 0.660, 0.593),
    (0.985, 0.763, 0.651),
    (0.990, 0.863, 0.727),
    (0.992, 0.942, 0.841),
    (0.987, 0.991, 0.750),
]


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _build_lut(ctrl_points: list[tuple[float, float, float]]) -> NDArray[np.float32]:
    """Linearly interpolate control points to a ``(256, 3)`` lookup table."""
    n = len(ctrl_points)
    t_ctrl = np.linspace(0.0, 1.0, n, dtype=np.float64)
    t_full = np.linspace(0.0, 1.0, 256, dtype=np.float64)

    arr = np.array(ctrl_points, dtype=np.float64)
    lut = np.empty((256, 3), dtype=np.float32)
    for c in range(3):
        lut[:, c] = np.interp(t_full, t_ctrl, arr[:, c]).astype(np.float32)

    return np.clip(lut, 0.0, 1.0)


def _load_colormaps() -> dict[str, NDArray[np.float32]]:
    """Load colormaps, preferring matplotlib for exact values."""
    try:
        import matplotlib

        maps: dict[str, NDArray[np.float32]] = {}
        for name in ("viridis", "inferno", "magma"):
            cmap = matplotlib.colormaps[name].resampled(256)
            rgba: NDArray[np.float32] = cmap(np.linspace(0.0, 1.0, 256))
            maps[name] = rgba[:, :3].astype(np.float32)
        return maps
    except (ImportError, AttributeError):
        pass

    # Fallback: interpolate from control points.
    return {
        "viridis": _build_lut(_VIRIDIS_CTRL),
        "inferno": _build_lut(_INFERNO_CTRL),
        "magma": _build_lut(_MAGMA_CTRL),
    }


# ---------------------------------------------------------------------------
# Module-level constants
# ---------------------------------------------------------------------------

_COLORMAPS: dict[str, NDArray[np.float32]] = _load_colormaps()

VIRIDIS: NDArray[np.float32] = _COLORMAPS["viridis"]
"""Viridis colormap: 256x3 float32 lookup table."""

INFERNO: NDArray[np.float32] = _COLORMAPS["inferno"]
"""Inferno colormap: 256x3 float32 lookup table."""

MAGMA: NDArray[np.float32] = _COLORMAPS["magma"]
"""Magma colormap: 256x3 float32 lookup table."""

AVAILABLE_COLORMAPS: dict[str, NDArray[np.float32]] = {
    "viridis": VIRIDIS,
    "inferno": INFERNO,
    "magma": MAGMA,
}
"""Mapping from colormap name to its ``(256, 3)`` lookup table."""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def apply_colormap(
    gray: NDArray[np.float32],
    colormap: str = "inferno",
) -> NDArray[np.float32]:
    """Apply a colormap to a grayscale image.

    Args:
        gray: Grayscale image ``(H, W)`` with values in ``[0, 1]``.
        colormap: Name of the colormap (``"viridis"``, ``"inferno"``, or
            ``"magma"``).

    Returns:
        False-color RGB image ``(H, W, 3)`` with values in ``[0, 1]``.

    Raises:
        ValueError: If the colormap name is unknown or the input is not 2-D.
    """
    if colormap not in AVAILABLE_COLORMAPS:
        msg = f"Unknown colormap: '{colormap}'. Available: {sorted(AVAILABLE_COLORMAPS)}"
        raise ValueError(msg)

    if gray.ndim != 2:
        msg = f"Expected 2-D grayscale array, got shape {gray.shape}"
        raise ValueError(msg)

    lut = AVAILABLE_COLORMAPS[colormap]

    # Map [0, 1] → index [0, 255] and look up.
    indices = np.clip(gray * 255.0, 0.0, 255.0).astype(np.uint8)
    result: NDArray[np.float32] = lut[indices]
    return result
